sudo: required

serivces:
  - docker

before_install:
  - docker build -t ajay/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ajay/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-480321802861'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRECT_KEY"
  
